# see https://raw.githubusercontent.com/noborus/ov/master/ov.yaml
# see https://raw.githubusercontent.com/noborus/ov/master/ov-less.yaml

# QuitSmall: false # Quit if the file size is smaller than the terminal size.
# IsWriteOriginal: false # Write the original content when exiting.
# BeforeWriteOriginal: 0 # Write the number of lines before the current location when exiting.
# AfterWriteOriginal: 0 # Write the number of lines after the current location when exiting.
#
# CaseSensitive: false # Case sensitive search.
# SmartCaseSensitive: false # Case sensitive search if the search string contains uppercase characters.
# RegexpSearch: false # Regular expression search.
# Incsearch: true # Incremental search.
#
# MemoryLimit: -1 # The maximum number of lines that can be loaded into memory.
# MemoryLimitFile: 100 # The maximum number of lines that can be loaded into memory when opening a file.
#
# DisableMouse: false # Disable mouse support.
# DisableColumnCycle: false # Disable cycling when moving columns.
# DisableStickyFollow: false # Disable sticky follow mode.
#
# ViewMode: markdown # Default view mode.
#
# For ClipboardMethod, specify “OSC52” to copy using OSC52 (if the terminal supports it).
# ClipboardMethod: "default" # Clipboard method. Options: "OSC52" or other.
#
# SetTerminalTitle: false # Set terminal title to display filename.
#
# Debug: false # Debug mode.
#
# ShrinkChar: '…' # Characters displayed when the column is shrinking.
#
# ReadWaitTime: 1s # Time to wait for a search while reading. 1s is the default.
#
General:
  TabWidth: 8
  Header: 0
  AlternateRows: false
  ColumnMode: false
  LineNumMode: false
  WrapMode: true
  ColumnDelimiter: ","
  MarkStyleWidth: 1
# HScrollWidth: 10%
# VScrollLines: 2
  Prompt:
    Normal:
#      ShowFilename: true # Show the filename.
#      InvertColor: true # Invert the color of the prompt.
#      ProcessOfCount: true # Show the process of count.
#      CursorType: 0 # Cursor type for the normal prompt.
    Input:
#      CursorType: 1 # Cursor type for the input prompt.

#  SectionDelimiter: "^#"
  # Style
  # String of the color name: Foreground, Background, UnderlineColor
  # Boolean: Bold, Blink, Dim, Italic, Underline
  # Number: UnderlineStyle
  Style:
    Alternate:
      Background: "gray"
    Header:
      Bold: true
    Body:
      # Add appropriate styles here
    LineNumber:
      Bold: true
    SearchHighlight:
      Reverse: true
    ColumnHighlight:
      Reverse: true
    MarkLine:
      Background: "darkgoldenrod"
    SectionLine:
      Background: "slateblue"
    VerticalHeader:
      # Add appropriate styles here
    Ruler:
      Background: "#333333"
      Foreground: "#CCCCCC"
      Bold: true
    HeaderBorder:
      # Add appropriate styles here
    SectionHeaderBorder:
      # Add appropriate styles here
    VerticalHeaderBorder:
      Background: "#c0c0c0"
    MultiColorHighlight:
      - Foreground: "red"
      - Foreground: "aqua"
      - Foreground: "yellow"
      - Foreground: "fuchsia"
      - Foreground: "lime"
      - Foreground: "blue"
      - Foreground: "grey"
    ColumnRainbow:
      - Foreground: "white"
      - Foreground: "crimson"
      - Foreground: "aqua"
      - Foreground: "lightsalmon"
      - Foreground: "lime"
      - Foreground: "blue"
      - Foreground: "yellowgreen"
    JumpTargetLine:
      Underline: true

StyleOverStrike:
  Bold: true
StyleOverLine:
  Underline: true

# WARNING: Empty keybinds don't work; their defaults will still be used.  If
# you see conflicts, set a useless keybind like F22 &c.
#
# Keybind
# Special key
#   "Enter","Backspace","Tab","Backtab","Esc",
#   "Delete", "Insert",
#   "Up", "Down", "Left", "Right", "Home", "End",
#   "F1...F64"
# Modifier key
#   "ctrl", "alt", "meta", "shift"
# Connect with modifier key + key
#   "ctrl+c"
KeyBind:
    exit:
        - "q"
        - "ctrl+c"
    cancel:
        - "Escape"
    write_exit:
        - "Q"
    set_write_exit:
    write_original:
    suspend:
        - "ctrl+z"
    edit:
    status_line:
    sync:
    reload:
        - "R"
    watch:
    watch_interval:
    follow_mode:
    follow_all:
    follow_section:
    help:
        - "?"
    logdoc:
    down:
        - "j"
        - "Down"
    up:
        - "k"
        - "Up"
    top:
        - "g"
        - "Home"
    bottom:
        - "G"
        - "End"
    left:
        - "h"
        - "left"
    right:
        - "l"
        - "right"
    half_left:
    half_right:
    page_up:
        - "PageUp"
    page_down:
        - "PageDown"
    page_half_up:
        - "ctrl+u"
    page_half_down:
        - " "
        - "ctrl+d"
    section_delimiter:
    section_start:
    section_header_num:
    hide_other:
        - "H"
    next_section:
        - "J"
    last_section:
    previous_section:
        - "K"
    mark:
        - "m"
    remove_mark:
        - "M"
    remove_all_mark:
        - "ctrl+delete"
    next_mark:
        - "ctrl+j"
    previous_mark:
        - "ctrl+k"
    set_view_mode:
    alter_rows_mode:
    line_number_mode:
        - "F11"
    search:
        - "/"
    wrap_mode:
        - "w"
        - "W"
    column_mode:
    backsearch:
        - "?"
    delimiter:
        - "d"
    header:
        - "F14"
    skip_lines:
        - "ctrl+s"
    tabwidth:
        - "t"
    goto:
        - "F21"
    next_search:
        - "n"
    next_backsearch:
        - "N"
    next_doc:
    previous_doc:
    toggle_mouse:
    multi_color:
        - "."
    jump_target:
        - "F22"
    plain_mode:
        - "ctrl+e"
    rainbow_mode:
        - "ctrl+r"
    close_file:
    width_left:
    width_right:
    begin_left:
    end_right:
    column_width:
    filter:
    close_doc:
    close_all_filter:
        - "F18"
    convert_type:
    align_format:
    raw_format:
    vertical_header:
    header_column:
    fixed_column:
    shrink_column:
    right_align:
    toggle_ruler:

    input_casesensitive:
    input_smart_casesensitive:
    input_incsearch:
    input_regexp_search:
    input_non_match:
    input_previous:
    input_next:
    input_copy:
    input_paste:

Mode:
  markdown:
    SectionDelimiter: "^#"
    WrapMode: true
    Style:
      SectionLine:
        Background: "blue"
  psql:
    Header: 2
    AlternateRows: true
    ColumnMode: true
    LineNumMode: false
    WrapMode: true
    ColumnDelimiter: "|"
  mysql:
    Header: 3
    AlternateRows: true
    ColumnMode: true
    LineNumMode: false
    WrapMode: true
    ColumnDelimiter: "|"

